### ISSUE TITLE
Getting this to work on my setup

### ISSUE THREAD

**Issue by OfficialBAMM** [CReimer/g910-gkey-uinput#1]
I've been trying for ages to get my g910 g/m keys to work. This repo seems to handle this issue

Current setup:
Tested with xev/showkey:
- My g keys are recognized as F keys.
- My m keys are unresponsive

Edited the file to get this usbcode(or whatever it is ^^):
Device('/sys/devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.1/0003:**046D:C32B.000B**/hidraw/hidraw1')
Device('/sys/devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/0003:**046D:C32B.000A**/hidraw/hidraw0')

It runs, but neither work. I've unplugged every usb and this is what remains, so I'm 99.99% sure that that is my g910.

I've read here: https://github.com/MatMoul/g810-led/issues/39 that you also use that repo. 
Is it neccecary?

If you have time, could you give me a push in the right direction?

**Comment by CReimer** [comment]
Yes. You need g810-led to disable the default mapping oft the g keys to f keys. After that it should work with the g910-gkey-uinput daemon.
